"""Change size datatype from Integer to BigInteger

Revision ID: 4861502428c5
Revises: 4c7101a6cead
Create Date: 2023-08-28 19:35:12.486556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4861502428c5'
down_revision: Union[str, None] = '4c7101a6cead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
